version: '3.7'

services:
  app:
    build:
      context: ./
      dockerfile: docker/Dockerfile.cpu
      args:
        user_name: $user_name
        group_name: $group_name
    image: $image_name
    container_name: $container_name
    tty: true
    volumes:
      - .:/home/$user_name/workspace
    working_dir: /home/$user_name/workspace
    environment:
      - MLFLOW_TRACKING_URI=sqlite:///result/mlflow.db
      # - MLFLOW_TRACKING_URI=http://localhost:5000/
    ports:
      - "5000:5000"   # MLflow
      - "6006:6006"   # tensorboard
      - "2022:22"     # sshd
      - "9000:9000"   # jupyter notebook on vscode
